spring:
  profiles:
    active: dev

greeting:
    message: Hello World!

---

spring:
  config:
    activate:
      on-profile: dev

greeting:
    message: Hello World! You are in DEV profile

---

spring:
  config:
    activate:
      on-profile: prod

greeting:
    message: Hello World! You are in PROD profile